//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DRSoftware_lib.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemGroup
    {
        public int IDGr { get; set; }
        public string NameGr { get; set; }
        public string TypGr { get; set; }
        public string GrDet { get; set; }
        public bool InUsed { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public int AddDate { get; set; }
        public byte[] Imag { get; set; }
    }
}
