//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DRSoftware_lib.DataBase.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public int ID { get; set; }
        public int FileDate { get; set; }
        public byte[] Image { get; set; }
        public string ItemName { get; set; }
        public int GroupID { get; set; }
        public int Type { get; set; }
        public int Unit { get; set; }
        public Nullable<int> Brcode { get; set; }
        public string Note { get; set; }
        public bool IsPriced { get; set; }
    }
}
